channels:
  - defaults
  - conda-forge
dependencies:
  - dask=0.18.2
  - fastparquet=0.1.5
  - jupyterlab=0.32.1
  - pandas=0.23.1
  - python=3.6.5
  - python-graphviz=0.8.2
  - python-snappy=0.5.2
  - scikit-learn=0.19.1
  - pip:
    - beautifulsoup4==4.9.1
    - click==7.1.2
    - doc8==0.8.0
    - flake8==3.8.1
    - flake8-bugbear==20.1.4
    - flake8-builtins==1.5.3
    - flake8-commas==2.0.0
    - flake8-comprehensions==3.2.2
    - flake8-deprecated==1.3
    - flake8-docstrings==1.5.0
    - flake8-per-file-ignores==0.8.1
    - flake8-print==3.1.4
    - flake8-quotes==3.2.0
    - flake8-todo==0.7
    - matplotlib==3.2.1
    - nbsphinx==0.7.0
    - pep8-naming==0.10.0
    - pybtex==0.22.2
    - pytest==5.4.2
    - pytest-black==0.3.9
    - pytest-cov==2.8.1
    - pytest-isort==1.0.0
    - pytest-pythonpath==0.7.3
    - sphinx==1.8.4
    - sphinx-rtd-theme==0.4.2
    - sphinxcontrib-bibtex==0.4.2
    - tox==3.7.0
    - tqdm==4.30.0
    - xlrd==1.2.0
