channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=0.31.4
  - lightgbm=2.1.0
  - pandas=0.23.0
  - pytest=3.6.0
  - python=3.6.4
  - python-graphviz=0.8.2
  - scikit-learn=0.19.1
  - sphinx=1.6.6
  - pip:
    - beautifulsoup4==4.6.0
    - click==6.7
    - doc8==0.8.0
    - feather-format==0.4.0
    - flake8==3.5.0
    - flake8-bugbear==18.2.0
    - flake8-commas==1.0.0
    - flake8-docstrings==1.3.0
    - flake8-per-file-ignores==0.5
    - flake8-polyfill==1.0.2
    - flake8-print==3.1.0
    - flake8-quotes==0.14.0
    - flake8-todo==0.7
    - missingno==0.4.0
    - nbsphinx==0.3.1
    - pep8-naming==0.5.0
    - pybtex==0.21
    - pytest-cov==2.5.1
    - pytest-pythonpath==0.7.2
    - shap==0.18.1
    - sphinx-rtd-theme==0.2.4
    - sphinxcontrib-bibtex==0.3.6
    - tox==2.9.1
