name: sp

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.8
  - pip
  - setuptools_scm
  - toml

  - pytask >=0.4.4
  - pytask-latex >=0.4
  - pytask-parallel >=0.4
  - universal_pathlib <0.2

  # Dependencies
  - black
  - dask
  - fastparquet
  - jupyterlab
  - nltk
  - pandas
  - python-graphviz
  - python-snappy
  - scikit-learn
  - beautifulsoup4
  - matplotlib
  - pre-commit
  - pytest
  - pytest-cov
  - tox
  - tqdm
  - openpyxl

  - pip:
    - -e .
