channels:
  - defaults
  - conda-forge
dependencies:
  - dask=0.18.2
  - fastparquet=0.1.5
  - jupyterlab=0.32.1
  - pandas=0.23.1
  - python=3.6.5
  - python-graphviz=0.8.2
  - python-snappy=0.5.2
  - scikit-learn=0.19.1
  - pip:
    - beautifulsoup4==4.7.1
    - click==7.0
    - doc8==0.8.0
    - flake8==3.7.5
    - flake8-bugbear==18.8.0
    - flake8-builtins==1.4.1
    - flake8-commas==2.0.0
    - flake8-comprehensions==2.0.0
    - flake8-deprecated==1.3
    - flake8-docstrings==1.3.0
    - flake8-per-file-ignores==0.8.1
    - flake8-print==3.1.0
    - flake8-quotes==1.0.0
    - flake8-todo==0.7
    - matplotlib==3.0.2
    - nbsphinx==0.4.1
    - pep8-naming==0.7.0
    - pybtex==0.22.0
    - pytest==4.0.2
    - pytest-black==0.3.2
    - pytest-cov==2.6.0
    - pytest-isort==0.2.1
    - pytest-pythonpath==0.7.3
    - sphinx==1.8.2
    - sphinx-rtd-theme==0.4.2
    - sphinxcontrib-bibtex==0.4.1
    - tox==3.6.0
    - tqdm==4.28.1
    - xlrd==1.2.0
