name: sp
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - fastparquet
  - jupyterlab
  - pandas
  - python-graphviz
  - python-snappy
  - scikit-learn
  - beautifulsoup4
  - click
  - matplotlib
  - nbsphinx
  - pre-commit
  - pybtex
  - pytest
  - pytest-cov
  - pytest-pythonpath
  - sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-bibtex
  - tox
  - tqdm
  - xlrd
