[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "software_patents"
classifiers = ["Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
requires-python = ">=3.8"
dependencies = ["pytask"]
dynamic = ["version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.check-manifest]
ignore = ["src/software_patents/_version.py"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false


[tool.setuptools_scm]
write_to = "src/software_patents/_version.py"


[tool.mypy]
files = ["src"]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "software_patents.analysis.transformers"
disallow_untyped_defs = false
ignore_errors = true


[tool.pytask.ini_options]
paths = "src/software_patents"


[tool.ruff]
target-version = "py38"
select = ["ALL"]
fix = true
extend-ignore = [
    "TRY",  # ignore tryceratops.
    "TCH",  # ignore non-guarded type imports.
    # Numpy docstyle
    "D107",
    "D203",
    "D212",
    "D213",
    "D402",
    "D413",
    "D415",
    "D416",
    "D417",
    # Others.
    "D404",  # Do not start module docstring with "This".
    "RET504",  # unnecessary variable assignment before return.
    "S101",  # raise errors for asserts.
    "B905",  # strict parameter for zip that was implemented in py310.
    "I",  # ignore isort
    "ANN101",  # type annotating self
    "ANN102",  # type annotating cls
    "FBT",  # flake8-boolean-trap
    "EM",  # flake8-errmsg
    "ANN401",  # flake8-annotate typing.Any
    "PD",  # pandas-vet
    "COM812",  # trailing comma missing, but black takes care of that
    "D401",  # imperative mood for first line. too many false-positives.
    "SLF001",  # access private members.
    "S603",
    "S607",

    # Temporary ignores.
    "ANN",
    "D",
    "S301",
]


[tool.ruff.pydocstyle]
convention = "numpy"


[tool.refurb]
python_version = "3.8"


[tool.pytest.ini_options]
addopts = ["--doctest-modules"]
testpaths = ["src"]
norecursedirs = [".idea", ".tox"]
filterwarnings = ["ignore:datetime.*:DeprecationWarning"]
