[project]
name = "software_patents"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only"
]
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4",
    "coiled",
    "dask",
    "httpx",
    "matplotlib",
    "nltk>=3.9.1",
    "openpyxl",
    "pandas",
    "pyarrow>=17.0.0",
    "pytask>=0.4.4",
    "pytask-latex",
    "pytask-parallel",
    "pytest",
    "pytest-cov",
    "s3fs>=2024.10.0",
    "scikit-learn",
    "universal-pathlib>=0.2.2",
]
dynamic = ["version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[dependency-groups]
typing = ["ty>=0.0.24"]

[build-system]
requires = ["hatchling", "hatch_vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.vcs]
version-file = "src/software_patents/_version.py"

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
only-packages = true

[tool.hatch.build.targets.wheel]
exclude = ["tests"]
only-packages = true

[tool.hatch.version]
source = "vcs"

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytask.ini_options]
paths = ["src/software_patents"]

[tool.ruff]
target-version = "py38"
fix = true
unsafe-fixes = true
extend-exclude = ["src/software_patents/exploration/*.ipynb"]

[tool.ruff.lint]
extend-ignore = [
    # Others.
    "ANN401",  # flake8-annotate typing.Any
    "PD",  # pandas-vet
    "COM812",  # Comply with ruff-format.
    "ISC001",  # Comply with ruff-format.
    # Temporary
    "D103",
    "D104",
    "TCH",
]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"*/test_*.py" = ["S101"]
"*/transformers.py" = ["ANN", "FBT", "D"]
"tests/*" = ["D", "ANN", "PLR2004"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.refurb]
python_version = "3.8"

[tool.pytest.ini_options]
addopts = ["--doctest-modules"]
testpaths = ["src"]
norecursedirs = [".idea", ".tox"]
filterwarnings = ["ignore:datetime.*:DeprecationWarning"]

[tool.ty.rules]
unused-ignore-comment = "error"

[[tool.ty.overrides]]
include = ["src/software_patents/__init__.py"]

[tool.ty.overrides.rules]
unresolved-import = "ignore"

[tool.ty.src]
include = ["src/software_patents"]
exclude = ["src/software_patents/exploration"]

[tool.ty.terminal]
error-on-warning = true
