from pathlib import Path


def build(ctx):
    # Copies the matplotlibrc file to the build directory. This file can be
    # used to make persistent customization to figures.
    # WARNING: Notice within the ``ctx(..)``, paths are relative to ``bld``
    # whereas in the ``build(...)``, they are relative to the ``wscript``.
    path_in = Path('..', 'src', 'figures', 'matplotlibrc')
    path_out = Path('matplotlibrc')

    ctx(
        rule=f'copy {str(path_in)} {str(path_out)}',
        deps=ctx.path_to(ctx, 'IN_FIGURES', path_in.name),
        target=ctx.path_to(ctx, 'BLD', path_in.name),
        name=f'copy_{path_in.stem}',
    )

    ctx(
        features='run_py_script',
        source='visualize_distribution_of_patents.py',
        deps=ctx.path_to(ctx, 'OUT_ANALYSIS',
                         'patents_classified_with_bh2007.pkl'),
        target=[
            ctx.path_to(ctx, 'OUT_FIGURES', 'fig_patents_distribution.png'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'fig_patents_distribution_vs.png'),
            ctx.path_to(ctx, 'OUT_FIGURES',
                        'fig_patents_distribution_vs_shares.png'),
        ],
        name='visualize_distribution_of_patents'
    )
