#!/usr/bin/env python


def build(ctx):

    ctx(
        features='run_py_script',
        source='classification_patents_catalogue_w_bh2007.py',
        deps=[ctx.path_to(ctx, 'OUT_DATA', 'database.hdf')],
        # target=[],
        name='classification_bh2007'
    )
